### ISSUE TITLE
Logstash not receiving data

### ISSUE THREAD

**Issue by bntjah** [sirsquidness/steam-discover#1]
As posted on Reddit:
"@sirsquidness seems as if it isn't dumping any data in logstash; is there any logs I can look in to where it dumps its data to ? I see the following 255.255.255.255 on iplogstash:somerandomport
The random port wasn't defined and I'm using a different subnetmask... in the config.json UDP is enabled IP is set to 127.0.0.1 (as its on the same device) Port is 9999 but I see a different port so if I could see where it possibly goes wrong it would be perfect.
I'm 100% sure that logstash works since I can dump data in the logstash using logger ...
Edit: Might clarify already tried debugmode but doesn't tell me all that much..."

Will post config.json later this evening

**Comment by sirsquidness** [comment]
As a test, stop logstash so the port is free and do  `nc -u -l 9999`, and see if steam-discover is sending any data to the port.

**Comment by bntjah** [comment]
Hey Sirsquidness already tried with: logger -P 9999 test and it comes through when steamdiscover isn't up; so I'm thinking it is indeed either config.json that isn't working or something I did wrong; but since there is not really a viable logging / debug mode I created this ticket

**Comment by sirsquidness** [comment]
The `nc` command will verify if steam-discover is sending anything at all - if it's invalid/malformed data, then logstash might be rejecting it. Or if it's sending nothing at all, `nc` will also tell us that. 

Also, the logstash man page has this to say:

```
     -d, --udp
              Use datagram (UDP) instead of the default stream connection
              (TCP).
```

So I think your logger command might be using TCP, not UDP - try adding the `-d` flag and see if that still works? 

I assume the logger command will be sending messages in the syslog protocol - steam-discover emits JSON encoded objects, one per UDP packet. I'm not sure how logstash is configured - it might be that if one port is configured to accept syslog messages, then anything other than syslog will break? 

Anyway, let me know how you go with that :)

**Comment by bntjah** [comment]
gvw@CU-ELK:~/steam-discover$ cat config.json
{
        "data-sinks": [
                {
                        "type": "postgres",
                        "enabled": false,
                        "options": {
                                "connectionString": "postgres://someuser:password@host/database"
                        }
                },
                {
                        "type": "udp",
                        "enabled": true,
                        "options": {
                                "udp6": true,
                                "host": "127.0.0.1",
                                "port": 9999
                        }
                },
                {
                        "type": "redis",
                        "enabled": false,
                        "options": {
                                "connectionString": null
                        }
                }
        ],
        "broadcastIntervalSeconds": 10,
        "steamApiKey": "steamapi",
        "enableDebugConsoleMessages": true,
        "broadcastOnAllInterfaces": true,
        "broadcastOnInterfaces": []
}
gvw@CU-ELK:~/steam-discover$ ifconfig
ens160    Link encap:Ethernet  HWaddr 00:0c:29:9c:a3:dd
          inet addr:10.0.1.25  Bcast:10.0.255.255  Mask:255.255.0.0
          inet6 addr: fe80::20c:29ff:fe9c:a3dd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:136986 errors:0 dropped:0 overruns:0 frame:0
          TX packets:57668 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:107918023 (107.9 MB)  TX bytes:5237262 (5.2 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1316855 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1316855 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:254748182 (254.7 MB)  TX bytes:254748182 (254.7 MB)

gvw@CU-ELK:~/steam-discover$ node app.js
sinkWrapper { sinks: [ udp { options: [Object], socket: [Object] } ] }
sending discovery packet - client broadcast discovery
Sending to address 255.255.255.255 on 10.0.1.25:27036

Will report back with the NC test & will have a look at my logstash if its in tcp or udp

Edit:
gvw@CU-ELK:/etc/logstash/conf.d$ cat 01-inputs.conf
input {
  udp {
    host => "127.0.0.1"
    port => 9999
    codec => "json"
commentedout  type => "steam" ### Might have forgotten this here?
  }
}

#tcp syslog stream via 5140
input {
  tcp {
    type => "syslog"
    port => 5140
  }
}
#udp syslogs tream via 5140
input {
  udp {
    type => "syslog"
    port => 5140
  }
}

Do note that the commentedout is actually a hashtag but github shows it otherwise in large

Edit2:
gvw@CU-ELK:/etc/logstash/conf.d$ sudo service logstash stop
gvw@CU-ELK:/etc/logstash/conf.d$ sudo nc -u -l 9999
^C
gvw@CU-ELK:/etc/logstash/conf.d$

Other SSH (while nc-u -l 9999 active):
gvw@CU-ELK:~/steam-discover$ node app.js
sinkWrapper { sinks: [ udp { options: [Object], socket: [Object] } ] }
sending discovery packet - client broadcast discovery
Sending to address 255.255.255.255 on 10.0.1.25:27036
!!!! Querying steam API for:  0
sending discovery packet - client broadcast discovery
Sending to address 255.255.255.255 on 10.0.1.25:27036

**Comment by sirsquidness** [comment]
Also try setting udp6 to false in the UDP sink config. I'm not sure if using a v6 socket but giving a v4 address is valid - I would think everything would crash and burn if it wasn't, but it's worth a shot anyway

**Comment by bntjah** [comment]
Hey Sirsquidness; already tried to disable udp6 sorry forgot to mention this...  result was the same :-S

**Comment by bntjah** [comment]
Possible something wrong somewhere in the code? Already tried to activate an extra input for the port 27036 but it remains the same...

**Comment by sirsquidness** [comment]
sorry, didn't see your edits in your previous post!

```
!!!! Querying steam API for: 0
sending discovery packet - client broadcast discovery
Sending to address 255.255.255.255 on 10.0.1.25:27036
```

This is our problem here - there's no steam clients replying, so there's no data to output to ELK. 

This is what it looks like when it finds a client:

```
sirsquidness@squid ~/projects/steam-discover $ node app.js 
sinkWrapper { sinks: [ udp { options: [Object], socket: [Object] } ] }
sending discovery packet - client broadcast discovery
Sending to address 255.255.255.255 on 10.0.0.100:27036
!!!! Querying steam API for:  1
Saw steam user SirSquidness
```

```
sirsquidness@squid ~/projects/steam-discover $ nc -l 9999 -u 
{"type":"client","data":{"version":8,"min_version":6,"connect_port":27036,"hostname":"vbox-vm","enabled_services":2,"ostype":10,"is64bit":true,"euniverse":1,"timestamp":1465824791,"screen_locked":false,"games_running":false,"mac_addresses":["{snip}"],"ip_address":"10.0.0.227","steamid":"{snip}","auth_key_id":{snip}}
```

On a PC on the same subnet which is running a logged in instance of steam, run `sudo tcpdump -i eth0 port 27036`, where eth0 is the system's LAN interface. Or you can use wireshark with the filter `udp.port == 27036`. Either of those is fine. On the system running steam discover, run the same thing. You should see on both systems a packet from 10.0.1.25:27036 to 255.255.255.255:27036. Then you should see on the steam discover system a packet in reply from every system on the subnet which is running steam to 10.0.1.25:27036.

On the steam discover host, you should can double check that the port is binding correctly - run `sudo netstat -nlp` and check that you see a line somewhat like this for every IP address that system has:

```
udp        0      0 10.0.0.100:27036        0.0.0.0:*                           6719/node       
```

Let me know how you go with that! :+1:

**Comment by bntjah** [comment]
No problem; test will be for after the weekend, As I'm going to a local lan with some friends. Thanks for taking the time to reply / investigate in to this.

I will report back with the results

Edit:

I can do tell that when it discovers me it doesn't transfer any data. But will test it tcpdump or wireshark...

**Comment by sirsquidness** [comment]
Hello again! 

I hope you had a great LAN :)

I just put together a script that builds and configures the required docker containers with the config /u/s0liddi created and verified it works. Kibana is still a black magic to me, so I haven't created a pretty graph, but there's definitely data in there. 

Have a look [here](https://github.com/OpenSourceLAN/steam-discover/tree/master/elk-graphing) and see if anything in there helps figure out what's wrong too.

**Comment by bntjah** [comment]
Most definitily was a solid / great LAN :-)
Will try it later on when I get back home; just started working (GMT+1) but thanks for trying to help me solve it! :-)

**Comment by bntjah** [comment]
I'm gonna close this since I haven't had the time to look in to this; and can't really tell when I might have the chance to look in to this. But thanks for the feedback though!

**Comment by sirsquidness** [comment]
No worries. When you find time, if you still need a hand you know where 
to find me! :)

**Comment by bntjah** [comment]
Just an update; with your Docker solution everything works without a hitch.
Now to begin learning how to visualize things in grafana :-)

**Comment by sirsquidness** [comment]
Awesome! I'd love to see what cool things you do with it :)

**Comment by bntjah** [comment]
Well I'm hoping s0liddi would like to share his JSON template so we have a example to base ourself on. Because can't seem to find much data on the grafana lucene query part yet...

**Comment by tardoe** [comment]
I’d be very interested in the Grafana templates too!

I am part of the Infrastructure team at RFLan - we run the largest LAN part in Australia (potentially the southern hemisphere) and we’d be very interested to pull some steam stats on what our attendees are playing ad-hoc.
- Tim

**Comment by sirsquidness** [comment]
I'll try and spend some time this week putting together a nice graph template, since the whole system is most useful if you also have some pretty graph to go with it. It makes sense to have some templates already available in the repo :)  If not Grafana, then maybe KIbana since I've been using that at work, so have some more familiarity with it.

@tardoe I understand you guys might be doing VLANs at your next event. The tool supports working across VLANs via a few methods, but I haven't tested them at a real event yet - so definitely verify it works in your environment ahead of time. But please don't hesitate to get in touch if it doesn't work!

**Comment by bntjah** [comment]
Sirsquidness, thanks for your input!
I've been trying to get something to work in Grafana but actually didn't get any further then seeing how many unique steam id's I had.

I replied to s0lidi's post requesting if he could / was willing to share his grafana templates but have yet to receive any reply.

I do have to say the tool you made (with the docker) is actually superb! It gives you a good insight in wich competitions might be worth considering for a next event...

**Comment by tardoe** [comment]
I’ll attempt to do some testing in isolation first and let you know.
- Tim
